// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjKB4cGyKq-gPc95CQ143NGKBhI12CU8s',
    appId: '1:875111844854:web:69d3c2ae6fb1a3691315d7',
    messagingSenderId: '875111844854',
    projectId: 'walletwatch-8f22f',
    authDomain: 'walletwatch-8f22f.firebaseapp.com',
    storageBucket: 'walletwatch-8f22f.appspot.com',
    measurementId: 'G-6C8YDZ2HX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqHiSssJCRCBo37LcUI6HrC1ifVKGHdR4',
    appId: '1:875111844854:android:d898397fa659067a1315d7',
    messagingSenderId: '875111844854',
    projectId: 'walletwatch-8f22f',
    storageBucket: 'walletwatch-8f22f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfoy3IzAJXbWWOiWp8wuW4OwQ2Hn_NQJQ',
    appId: '1:875111844854:ios:ad9a10f7bdb6e1001315d7',
    messagingSenderId: '875111844854',
    projectId: 'walletwatch-8f22f',
    storageBucket: 'walletwatch-8f22f.appspot.com',
    androidClientId:
        '875111844854-afjoilc6p9lttpvbccug1l4vbrfk726p.apps.googleusercontent.com',
    iosClientId:
        '875111844854-ccto82e0v0n4r23qtcdq82lraed0kap7.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfoy3IzAJXbWWOiWp8wuW4OwQ2Hn_NQJQ',
    appId: '1:875111844854:ios:ad9a10f7bdb6e1001315d7',
    messagingSenderId: '875111844854',
    projectId: 'walletwatch-8f22f',
    storageBucket: 'walletwatch-8f22f.appspot.com',
    androidClientId:
        '875111844854-afjoilc6p9lttpvbccug1l4vbrfk726p.apps.googleusercontent.com',
    iosClientId:
        '875111844854-ccto82e0v0n4r23qtcdq82lraed0kap7.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjKB4cGyKq-gPc95CQ143NGKBhI12CU8s',
    appId: '1:875111844854:web:e2e2a9a0d1c3d9a21315d7',
    messagingSenderId: '875111844854',
    projectId: 'walletwatch-8f22f',
    authDomain: 'walletwatch-8f22f.firebaseapp.com',
    storageBucket: 'walletwatch-8f22f.appspot.com',
    measurementId: 'G-PBE7K5Q7JV',
  );
}
